//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Language.Xml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Language.Xml.XmlResources", typeof(XmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML attribute &apos;{0}&apos; must appear before XML attribute &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_AttributeOrder {
            get {
                return ResourceManager.GetString("ERR_AttributeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML DTDs are not supported..
        /// </summary>
        internal static string ERR_DTDNotSupported {
            get {
                return ResourceManager.GetString("ERR_DTDNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate XML attribute &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_DuplicateXmlAttribute {
            get {
                return ResourceManager.GetString("ERR_DuplicateXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;&apos; expected..
        /// </summary>
        internal static string ERR_ExpectedGreater {
            get {
                return ResourceManager.GetString("ERR_ExpectedGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected beginning &apos;&lt;&apos; for an XML tag..
        /// </summary>
        internal static string ERR_ExpectedLT {
            get {
                return ResourceManager.GetString("ERR_ExpectedLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected matching closing double quote for XML attribute value..
        /// </summary>
        internal static string ERR_ExpectedQuote {
            get {
                return ResourceManager.GetString("ERR_ExpectedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected closing &apos;;&apos; for XML entity..
        /// </summary>
        internal static string ERR_ExpectedSColon {
            get {
                return ResourceManager.GetString("ERR_ExpectedSColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected matching closing single quote for XML attribute value..
        /// </summary>
        internal static string ERR_ExpectedSQuote {
            get {
                return ResourceManager.GetString("ERR_ExpectedSQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML name expected..
        /// </summary>
        internal static string ERR_ExpectedXmlName {
            get {
                return ResourceManager.GetString("ERR_ExpectedXmlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required white space..
        /// </summary>
        internal static string ERR_ExpectedXmlWhiteSpace {
            get {
                return ResourceManager.GetString("ERR_ExpectedXmlWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML declaration does not allow attribute &apos;{0}{1}{2}&apos;..
        /// </summary>
        internal static string ERR_IllegalAttributeInXmlDecl {
            get {
                return ResourceManager.GetString("ERR_IllegalAttributeInXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is not valid..
        /// </summary>
        internal static string ERR_IllegalChar {
            get {
                return ResourceManager.GetString("ERR_IllegalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML processing instruction name &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ERR_IllegalProcessingInstructionName {
            get {
                return ResourceManager.GetString("ERR_IllegalProcessingInstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character sequence &apos;--&apos; is not allowed in an XML comment..
        /// </summary>
        internal static string ERR_IllegalXmlCommentChar {
            get {
                return ResourceManager.GetString("ERR_IllegalXmlCommentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character &apos;{0}&apos; ({1}) is not allowed in an XML name..
        /// </summary>
        internal static string ERR_IllegalXmlNameChar {
            get {
                return ResourceManager.GetString("ERR_IllegalXmlNameChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character &apos;{0}&apos; ({1}) is not allowed at the beginning of an XML name..
        /// </summary>
        internal static string ERR_IllegalXmlStartNameChar {
            get {
                return ResourceManager.GetString("ERR_IllegalXmlStartNameChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White space cannot appear here..
        /// </summary>
        internal static string ERR_IllegalXmlWhiteSpace {
            get {
                return ResourceManager.GetString("ERR_IllegalXmlWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value is not valid; expecting &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_InvalidAttributeValue1 {
            get {
                return ResourceManager.GetString("ERR_InvalidAttributeValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value is not valid; expecting &apos;{0}&apos; or &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_InvalidAttributeValue2 {
            get {
                return ResourceManager.GetString("ERR_InvalidAttributeValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End tag &lt;/{0}{1}{2}&gt; expected..
        /// </summary>
        internal static string ERR_MismatchedXmlEndTag {
            get {
                return ResourceManager.GetString("ERR_MismatchedXmlEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required attribute &apos;version&apos; missing from XML declaration..
        /// </summary>
        internal static string ERR_MissingVersionInXmlDecl {
            get {
                return ResourceManager.GetString("ERR_MissingVersionInXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is missing an end tag..
        /// </summary>
        internal static string ERR_MissingXmlEndTag {
            get {
                return ResourceManager.GetString("ERR_MissingXmlEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML namespace prefix &apos;{0}&apos; is reserved for use by XML and the namespace URI cannot be changed..
        /// </summary>
        internal static string ERR_ReservedXmlPrefix {
            get {
                return ResourceManager.GetString("ERR_ReservedXmlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected quoted XML attribute value or embedded expression..
        /// </summary>
        internal static string ERR_StartAttributeValue {
            get {
                return ResourceManager.GetString("ERR_StartAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error..
        /// </summary>
        internal static string ERR_Syntax {
            get {
                return ResourceManager.GetString("ERR_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML attribute &apos;version&apos; must be the first attribute in XML declaration..
        /// </summary>
        internal static string ERR_VersionMustBeFirstInXmlDecl {
            get {
                return ResourceManager.GetString("ERR_VersionMustBeFirstInXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The literal string &apos;]]&gt;&apos; is not allowed in element content..
        /// </summary>
        internal static string ERR_XmlEndCDataNotAllowedInContent {
            get {
                return ResourceManager.GetString("ERR_XmlEndCDataNotAllowedInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML end element must be preceded by a matching start element..
        /// </summary>
        internal static string ERR_XmlEndElementNoMatchingStart {
            get {
                return ResourceManager.GetString("ERR_XmlEndElementNoMatchingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML entity references are not supported..
        /// </summary>
        internal static string ERR_XmlEntityReference {
            get {
                return ResourceManager.GetString("ERR_XmlEntityReference", resourceCulture);
            }
        }
    }
}
